version: '3.1'
services:
  stat-service:
    build: ewm-stat-service/stat-service
    image: stat-service
    container_name: stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/ewm-stat
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASSWORD=user

  stat-db:
    image: postgres:14-alpine
    container_name: stat-db
    environment:
      - POSTGRES_DB=ewm-stat
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user

  ewm-service:
    build: ewm-main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stat-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASSWORD=user
      - stat-service.url=http://stat-service:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
